Added ChatStyle
BeeTech-global/flutter_zendesk_chat pull request #6
Opened 2019-10-17 10:56 UTC by DavidFD005

Added customisable chat style.

You can create styles and use the `copyWith()` to change some parameters for example:

![image](https://user-images.githubusercontent.com/23307893/67003031-6ab20100-f0dd-11e9-90b4-f9998c1880f7.png)

For example in this case the secondary style will get all the main style with the main color changed

2019-10-17 15:31 UTC, zeucxb requested changes

2019-10-17 15:31 UTC, zeucxb commented on lib/widgets/zendesk_chat_widget.dart
> +class ChatStyle {
Remove from this file, please create at models

2019-10-17 15:31 UTC, zeucxb commented on lib/widgets/zendesk_chat_widget.dart
> +                    style: chatStyle.descriptionTextStyle,
Isn't messageTextStyle a better name?

2019-10-18 07:33 UTC, DavidFD005 commented on lib/widgets/zendesk_chat_widget.dart
> +class ChatStyle {
It is not a model itself, It is a style class only used on this widget so I think that it is ok to leave it here

2019-10-18 07:33 UTC, davidfranquet commented on lib/widgets/zendesk_chat_widget.dart
> +                    style: chatStyle.descriptionTextStyle,
yep

2019-10-18 07:45 UTC, DavidFD005 commented
Done

2019-10-18 15:45 UTC, zeucxb requested changes

2019-10-18 15:45 UTC, zeucxb commented on lib/widgets/zendesk_chat_widget.dart
> +const ChatStyle _defaultStyle = const _DefaultStyle();
With this approach if I set just `mainColor` in the `chatStyle` all the defaultStyle will be replaced, it's ok. But in this case ChatStyle properties must be required and `assert` to not null.

2019-10-18 15:45 UTC, zeucxb commented on lib/models/chat_style.dart
> +}
[LINT]: Missing new line at the end.

2019-10-18 15:45 UTC, zeucxb commented on lib/widgets/zendesk_chat_widget.dart
> +  final Color mainColor = Colors.blue;
DefaultStyle must follow theme colours.

2019-10-18 15:45 UTC, zeucxb commented on lib/widgets/zendesk_chat_widget.dart
> +                      style: chatStyle.nameTextStyle,
Will it be the same for visitor and main?

2019-10-18 15:45 UTC, zeucxb commented on lib/widgets/zendesk_chat_widget.dart
> +                    style: chatStyle.messageTextStyle,
Same here: Will it be the same for visitor and main?

2019-10-18 15:46 UTC, zeucxb commented
@DavidFD005 Thank you for your help. And sorry for being boring 😞

2019-10-18 15:48 UTC, zeucxb commented on lib/widgets/zendesk_chat_widget.dart
> +class ChatStyle {
But it's the package core widget. And it need to be exported.

2019-10-18 15:52 UTC, zeucxb commented
@DavidFD005 One last thing. You need to add chat_settings_model to models file to export. It would be nice to use ChatStyle in example, so you can check if it's everything exported and ok. 👌

2019-10-21 07:53 UTC, DavidFD005 commented
I will do all this stuff today

2019-10-21 14:36 UTC, lucasdaiki approved these changes

2019-10-21 14:38 UTC, lucasdaiki approved these changes

2019-10-21 14:42 UTC, lucasdaiki requested changes
❤️

2019-10-21 17:23 UTC, lucasdaiki approved these changes

2019-10-23 18:20 UTC, zeucxb commented
@DavidFD005 => Are you still working on it?

2019-10-29 17:03 UTC, closed without merging